# Generated by Django 4.2.2 on 2023-06-28 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('Created', 'Created'), ('InDelivery', 'InDelivery'), ('Finished', 'Finished')], max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('On Delivery', 'On Delivery'), ('Card', 'Card')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('technology', models.CharField(max_length=255)),
                ('dimensions', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('chipset', models.CharField(max_length=255)),
                ('CPU', models.CharField(max_length=255)),
                ('GPU', models.CharField(max_length=255)),
                ('memory', models.CharField(max_length=255)),
                ('main_camera', models.CharField(max_length=255)),
                ('front_camera', models.CharField(max_length=255)),
                ('battery', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MobileXpress.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneColorQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MobileXpress.color')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MobileXpress.phone')),
            ],
        ),
        migrations.AddField(
            model_name='phone',
            name='colors',
            field=models.ManyToManyField(through='MobileXpress.PhoneColorQuantity', to='MobileXpress.color'),
        ),
        migrations.AddField(
            model_name='phone',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MobileXpress.manufacturer'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard')], max_length=100)),
                ('card_number', models.CharField(max_length=255)),
                ('exp_mm', models.IntegerField(max_length=2)),
                ('exp_yy', models.IntegerField(max_length=2)),
                ('security_code', models.IntegerField(max_length=3)),
                ('card_holder_name', models.CharField(max_length=255)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MobileXpress.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MobileXpress.shoppingcart'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MobileXpress.customuser'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MobileXpress.shoppingcart')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MobileXpress.phone')),
            ],
        ),
    ]
