# Generated by Django 4.2.2 on 2023-06-28 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MobileXpress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='colors',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MobileXpress.color'),
        ),
    ]
