# Generated by Django 4.2.2 on 2023-06-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileXpress', '0002_remove_phone_colors_cartitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='phone',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exp_mm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exp_yy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='security_code',
            field=models.IntegerField(),
        ),
    ]
