# Generated by Django 4.2.2 on 2023-06-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileXpress', '0003_phone_phone_alter_payment_exp_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='colors/'),
        ),
    ]
